Practica 5.3/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAL;

namespace Practica_5._3.Controllers
{
    public class ProductosController : Controller
    {
        private CatalogoDataModel db = new CatalogoDataModel();

        // GET: Productos
        public ActionResult Index()
        {
            return View(db.Producto.ToList());
        }

        // GET: Productos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // GET: Productos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Productos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.

        //public ActionResult Create([Bind(Include = "IdProducto,Producto1,Descripcion,Precio,CantExistencia,ImageUrl")] Producto producto)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Producto.Add(producto);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(producto);
        //}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase file)
        {
            // FILE
            string ImageName = System.IO.Path.GetFileName(file.FileName);
            string physicalPath = Server.MapPath("~/images/" + ImageName);
            file.SaveAs(physicalPath);

            // PRODUCTO
            Producto pro = new Producto();
            pro.Producto1 = Request.Form["Producto1"];
            pro.Descripcion = Request.Form["Descripcion"];
            pro.Precio = float.Parse(Request.Form["Precio"]);
            pro.CantExistencia = int.Parse(Request.Form["CantExistencia"]);
            pro.ImageUrl = ImageName;
            
            // ENTITY
            db.Producto.Add(pro);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Productos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HttpPostedFileBase file)
        {
            Producto pro = new Producto();

            if (ModelState.IsValid)
            {
                // FILE
                string ImageName = System.IO.Path.GetFileName(file.FileName);
                string physicalPath = Server.MapPath("~/images/" + ImageName);
                file.SaveAs(physicalPath);

                // PRODUCTO
                pro.IdProducto = int.Parse(Request.Form["Id"]);
                pro.Producto1 = Request.Form["Producto1"];
                pro.Descripcion = Request.Form["Descripcion"];
                pro.Precio = float.Parse(Request.Form["Precio"]);
                pro.CantExistencia = int.Parse(Request.Form["CantExistencia"]);
                pro.ImageUrl = ImageName;

                db.Entry(pro).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(pro);
        }

        //// POST: Productos/Edit/5
        //// Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        //// más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "IdProducto,Producto1,Descripcion,Precio,CantExistencia,ImageUrl")] Producto producto)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(producto).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(producto);
        //}

        // GET: Productos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Producto producto = db.Producto.Find(id);
            db.Producto.Remove(producto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Practica 5.3/Views/Productos/Create.cshtml
@model DAL.Producto

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>


@using (Html.BeginForm("Create", "Productos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Productos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Producto1, "Producto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Producto1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Producto1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CantExistencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CantExistencia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CantExistencia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" id="file" class="form-control btn-success" />
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <a href="/Productos/" class="btn btn-info">Regresar</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Practica 5.3/Views/Productos/Delete.cshtml
@model DAL.Producto

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>¿Está seguro que desea eliminar este registro?</h3>
<div>
    <h4>Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
        </dt>
        <dd>
            <img src="~/images/@Model.ImageUrl" alt="Imagen" width="90" height="90" />
        </dd>

        <dt>
            @Html.DisplayName("Producto")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Producto1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

        <dt>
            @Html.DisplayName("Existencia")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CantExistencia)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" />
            <a href="/Productos/" class="btn btn-info">Regresar</a>
        </div>
    }
</div>

Practica 5.3/Views/Productos/Details.cshtml
@model DAL.Producto

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
        </dt>
        <dd>
            <img src="~/images/@Model.ImageUrl" alt="Imagen" width="90" height="90" />
        </dd>

        <dt>
            @Html.DisplayName("Producto")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Producto1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

        <dt>
            @Html.DisplayName("Existencia")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CantExistencia)
        </dd>
    </dl>
</div>
<p>
    <a href="/Productos/Edit/?id=@Model.IdProducto" class="btn btn-primary">Editar</a>
    <a href="/Productos/" class="btn btn-info">Regresar</a>
</p>

Practica 5.3/Views/Productos/Edit.cshtml
@model DAL.Producto

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm("Edit", "Productos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Producto</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdProducto)
    <input type="hidden" name="Id" value="@Model.IdProducto" />
    <div class="form-group">
        @Html.LabelFor(model => model.Producto1, "Producto", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Producto1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Producto1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CantExistencia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CantExistencia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CantExistencia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="file" id="file" class="form-control btn-success" />
            @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    <a href="/Productos/" class="btn btn-info">Regresar</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Practica 5.3/Views/Productos/Index.cshtml
@model IEnumerable<DAL.Producto>

@{
    ViewBag.Title = "Productos";
}

<h2>Productos</h2>

<div class="row">
    <div class="col-sm-2">
        <a href="/Productos/Create" style="margin-bottom: 10px" class="btn btn-success">Nuevo</a>
    </div>
    <div>
        <input type="text" name="search" placeholder="Busqueda..." class="form-control" id="input_search" />
    </div>
</div>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Imagen")
            </th>
            <th>
                @Html.DisplayName("Producto")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantExistencia)
            </th>
            <th></th>
        </tr>
    </thead> 
    <tbody id="table_body">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="~/images/@item.ImageUrl" alt="Imagen" width="90" height="90" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Producto1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Precio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CantExistencia)
                </td>
                <td>
                    <a href="/Productos/Edit/?id=@item.IdProducto" class="btn btn-primary">Editar</a>
                    <a href="/Productos/Details/?id=@item.IdProducto" class="btn btn-warning">Detalles</a>
                    <a href="/Productos/Delete/?id=@item.IdProducto" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{
    <script>
        $(document).ready(function () {
            $("#input_search").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#table_body tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
                });
            });
        });
    </script>
}